function join_AuthorsEditors(AUTHFILE, EDITORFILE, OUTFILE)

%% Join authorial and editorial stdist information into a single file.

% -- ingest
authors = readtable(AUTHFILE);
editors = readtable(EDITORFILE);

% -- prep editors
editors = editors(:,{...
	'Journal' 'n_1st2nd_affiliations' ...
	'journal_geomean_lat_1st2nd' 'journal_geomean_lon_1st2nd' ...
	'journal_stdist_linear_1st2nd_km' 'journal_stdist_linear_1st2nd_deg'});
editors.Properties.VariableNames = {...
	'Journal' 'n_affiliations' ...
	'journal_geomean_lat' 'journal_geomean_lon' ...
	'journal_stdist_linear_km' 'journal_stdist_linear_deg'};

% -- prep authors
authors =  authors(:,{...
	'Journal' 'n_affiliations' ...
	'journal_geomean_lat' 'journal_geomean_lon' ...
	'journal_stdist_linear_km' 'journal_stdist_linear_deg'});

% -- join
J = innerjoin(editors,authors,'Keys','Journal');

% -- calc author--editor geomean 'tension'
% thanks: https://www.mathworks.com/help/map/ref/distance.html
J.arclen_author_editor = distance(...
	J.journal_geomean_lat_editors,J.journal_geomean_lon_editors,...
	J.journal_geomean_lat_authors,J.journal_geomean_lon_authors);

% -- write
writetable(J, OUTFILE);
